version: "2"
services:
  node:
    image: "node:8"
    user: "root"
    working_dir: /Users/ralph/Workspaces/cavalion.org/cavalion-server/docker-compose
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/Users/ralph/Workspaces/cavalion.org/cavalion-server/docker-compose
    ports:
      - "4410:4410"
    expose:
      - "4410"
    command: "npm start"